hendriknielaender/double-trouble

- data/blog/gitlab_review_apps_aws_vite.md
> Draft: New post on review apps

- astro.config.mjs
- src/assets/styles/base.css
https://github.com/hendriknielaender/double-trouble/issues/25
> feat: code theme to rose-pine and line numbers

- src/assets/styles/base.css
- src/components/blog/SinglePost.astro
- src/utils/clipboard.js
- smaller line height
- add copy to clipboard icon
- add small border around code block
> feat: add copy to clipboard

- src/components/widgets/Footer.astro
- src/pages/privacy.astro
https://github.com/hendriknielaender/double-trouble/issues/12
> feat: add privacy police

- src/components/widgets/Footer.astro
- src/pages/legal.astro
https://github.com/hendriknielaender/double-trouble/issues/13
> feat: add legal notice

- src/assets/styles/base.css
https://github.com/hendriknielaender/double-trouble/issues/25
> fix: large screen code line-height

- src/components/core/BasicScripts.astro
motivation is that our light mode sucks xd
> feat: set dark mode as the default

- src/components/blog/SinglePost.astro
- src/components/widgets/Header.astro
- src/layouts/BaseLayout.astro
Everything in this PR is up for discussion, just a few suggested edits here and there. Let's merge it if we like it 😃
> Fix: Adapt Styles

- data/blog/product_engineers.md
Everything in here is just a suggestion ✨
> fix: post-publish edits on product engineer post

- data/blog/product_engineers.md
- src/components/atoms/TwitterComments.astro
- src/components/blog/SinglePost.astro
- src/components/core/BasicScripts.astro
- src/utils/posts.js
Features:
- optionally adds tweets as comments
- tweets respect the theme (on page load and after theme toggle)
> feat: add tweet comments [#33]

- README.md
- src/layouts/BaseLayout.astro
Just took the one with more colors. Great suggestions! 💪🏻 (Credentials in our blog vault)
Relates to #44
> feat: move from panelbear to usermaven

- astro.config.mjs
> fix: add redirect for berlin summit post after rename [#176]

- data/blog/bun-release.md
Started also an example project over here using the aws-sdk: https://gitlab.com/flyck/hype-js/-/tree/main/bun
> Fixup bun lambda post

- src/components/blog/HighlightedPosts.astro
- src/pages/index.astro
https://github.com/hendriknielaender/double-trouble/assets/51416554/3a6c85e5-790b-44ac-bcdd-482e111ff388
> feat: logo animation

- src/assets/styles/base.css
- src/components/blog/Grid.astro
- src/components/blog/HighlightedPosts.astro
- src/components/blog/ListItem.astro
- src/components/widgets/Footer.astro
- src/components/widgets/Header.astro
I feel the design is not as nice as it could be. Made some random changes. Looks better? (left: before, right: after)
Changes:
- currently only in white mode the header is transparent, now also in dark mode (has cool effect when reading a blogpost!)
- dark mode header now was a tiny border
- footer has a different color
- there is more of a margin between the highlighted posts on the main page and the footer
- less margins on the codeblocks, right now they seem a bit puffy (🤣)
> fix(design): improve design slightly

- src/components/blog/SinglePost.astro
> fix(design): image credit aligns properly

- src/components/core/BasicScripts.astro
switching to light mode has not been saved properly to localstorage
> fix: dark mode toggle

- data/blog/optimal-pipeline-setup.md
> chore: add more code examples & links to cicd post

- src/components/core/BasicScripts.astro
- src/layouts/BaseLayout.astro
- hamburger menu works still even after transitions
- dark mode toggle works as it does currently
- discovered a bug in tweet backgrounds not being refreshed on toggle
- no black or white flashes during the transition
Closes #221
> feat: add back view transitions

- src/layouts/BaseLayout.astro
https://usermaven.com/docs/integrations/javascript#add-tracking-pixel
> fix: usermaven in view transition spa mode

- astro.config.mjs
- biome.json
- plugins/rehype-autolink-config.ts
- src/components/atoms/InfoText.tsx
- src/components/atoms/RankingTable.tsx
- src/config.mjs
- src/pages/rss.xml.js
- src/utils/clipboard.js
- src/utils/directories.js
- src/utils/frontmatter.js
- src/utils/images-optimization.js
- src/utils/images.js
- src/utils/permalinks.js
- src/utils/posts.js
- src/utils/utils.js
- tailwind.config.cjs
before, indentation rules only applied to json files. now we have them also for js / ts (no tabs, 2 instead of 8 spaces)
> chore: fix indentation

- src/layouts/BaseLayout.astro
- src/layouts/PageLayout.astro
> fix: about section layout

- data/blog/analyzing-gitlab-metrics-sqlite-grafana-guide.md
- data/blog/optimal-pipeline-setup.md
Revisting some older posts I came up with some rewordings for a hopefully better reading flow.
> chore: reword grafana & cicd post
